export enum ScreenName {
  HOME = 'HOME',
  INTRO = 'INTRO',
  SIGN_UP = 'SIGN_UP',
  LOG_IN = 'LOG_IN',
  CONFIRM_SIGN_UP = 'CONFIRM_SIGN_UP',
  FORGOT_PASSWORD = 'FORGOT_PASSWORD',
  CONFIRM_FORGOT_PASSWORD = 'CONFIRM_FORGOT_PASSWORD',
}
