export enum ScreenName {
  HOME = 'HOME',
  SIGN_UP = 'SIGN_UP',
  SIGN_IN = 'SIGN_IN',
  CONFIRM_SIGN_UP = 'CONFIRM_SIGN_UP',
  FORGOT_PASSWORD = 'FORGOT_PASSWORD',
  CONFIRM_FORGOT_PASSWORD = 'CONFIRM_FORGOT_PASSWORD',
}
